### ISSUE TITLE
What else do I need to do?

### ISSUE THREAD

**Issue by fkue587** [nebelorz/NW-Auto-Fishing#10]
What is the reason for this.
My friend has installed python 3.10

So I installed PyCharm for him 
Use PyCharm to install various libraries and packages.

What else do I need to do? He still doesn't work.

**Comment by fkue587** [comment]
![微信图片_20220103194401](https://user-images.githubusercontent.com/93835049/147957551-8856f6b2-3d2f-45ca-9064-5b714ed3a41f.png)

**Comment by nebelorz** [comment]
Everything what's needed is to install Python and pyDirectInput and pyAutoGUI.

The error showing is that you need to install the Pillow package.
On the command line:
`python3 -m pip install --upgrade pip`
`python3 -m pip install --upgrade Pillow`

**Comment by fkue587** [comment]
The openCV library is installed 
solved the problem.
pip install opencv-python
