### ISSUE TITLE
check for bugged cast

### ISSUE THREAD

**Issue by qq1ng** [nebelorz/NW-Auto-Fishing#11]
feel free to label this as request.

New World bugs out when fishing quite often for me, leaving me wih my floater in the water & no fishing indicator up.
This could be avoided by a check like "didnt do anything for (max time it could take a fish to bite) -> restart".
Just an idea, as you seem to be adding new features constantly.

**Comment by nebelorz** [comment]
Hello @qq1ng!
It happened me beforeand the only solution was to reconnect, but it never disappeared after it was already been shown :/

At this moment I cannot add anything due to lack of time (working and studying exams), but I will take a look at this in the future.

**Comment by bad1dea** [comment]
If your indicators are missing (Fishing) it's usually due to resolution change..

Pressing ESC and/or bringing up inventory will bring the UI Back.

**Comment by fkue587** [comment]
Occasionally there are no fishing indicators due to game bugs.
In this case, you need to exit to the menu again, and then re-enter the game will be fine.
Opening the backpack does not solve this problem.
Only re-enter the game.

**Comment by fkue587** [comment]
![微信截图_20220119003741](https://user-images.githubusercontent.com/93835049/149981115-645c8813-b1ec-4295-92f6-ab7da8dd61a9.png)
I've recently noticed a lot of bots placing items in the auction house.
The price is 0.01 iron ore or other minerals.
I refreshed once a second to buy these items.
But I will keep a lot of .01 items for the bots to keep listing them.
My eyes get tired and I can't look at the auction house for long.
So is it possible to make a bot that scans items and buys them?
The function is as follows
1. Buy items below a custom price. For example, I only buy items under 0.02
2. Keep a quantity of 1 or 10 items after purchase. Customize the number of reserved items.
This will allow the robot to continue to list items.
3. Customize for X seconds. Automatically refresh the auction house. 
4. Do not buy items in the blacklist.
5. Customize the purchase list to -----RESOURCE----Raw Resources
6. Prevent AFK

This is not urgent. Just want to use it as a programming sweet spot.

**Comment by bad1dea** [comment]
> Occasionally there are no fishing indicators due to game bugs. In this case, you need to exit to the menu again, and then re-enter the game will be fine. Opening the backpack does not solve this problem. Only re-enter the game.

Make a video, of you having missing indicators ... press ESC (Bring up menu/screen) and press ESC again and the UI will come back... it's an official work around posted on forum.. and has worked for me 100% of the time.

**Comment by bad1dea** [comment]
> 

I add a timer after casting/finding indicator -- for 90 seconds (should never take more than 90 seconds after cast to catch a fish) if the timer hits -- right click (cancels fishing) --> hit ESC x 2 (To reset UI) --> continue to next loop.

I can do PR if you want since you're busy..

**Comment by qq1ng** [comment]
> ![微信截图_20220119003741](https://user-images.githubusercontent.com/93835049/149981115-645c8813-b1ec-4295-92f6-ab7da8dd61a9.png) I've recently noticed a lot of bots placing items in the auction house. The price is 0.01 iron ore or other minerals. I refreshed once a second to buy these items. But I will keep a lot of .01 items for the bots to keep listing them. My eyes get tired and I can't look at the auction house for long. So is it possible to make a bot that scans items and buys them? The function is as follows
> 
> 1. Buy items below a custom price. For example, I only buy items under 0.02
> 2. Keep a quantity of 1 or 10 items after purchase. Customize the number of reserved items.
>    This will allow the robot to continue to list items.
> 3. Customize for X seconds. Automatically refresh the auction house.
> 4. Do not buy items in the blacklist.
> 5. Customize the purchase list to -----RESOURCE----Raw Resources
> 6. Prevent AFK
> 
> This is not urgent. Just want to use it as a programming sweet spot.

pls open a new issue for this instead of hijacking the thread. I also don't think this has anything to do with the fishing bot in general.

**Comment by nebelorz** [comment]
> > 
> 
> I add a timer after casting/finding indicator -- for 90 seconds (should never take more than 90 seconds after cast to catch a fish) if the timer hits -- right click (cancels fishing) --> hit ESC x 2 (To reset UI) --> continue to next loop.
> 
> I can do PR if you want since you're busy..

That's a solution and will absolutely work, but I like to approach a clean solution to it, making a check and therefore if it's true, calling a function that does what you describe and so on.

I don't want to be mean or impolite, don't take it bad, but I don't know how do you code, if you've made it to just work and didn't care about readability, clean code etc. so I'm not sure if we could do a PR.

Anyway, if it solves @qq1ng issue and if he/she trusts it and wants to use your build, just get in touch  😋

**Comment by fkue587** [comment]
> > ![微信截图_20220119003741](https://user-images.githubusercontent.com/93835049/149981115-645c8813-b1ec-4295-92f6-ab7da8dd61a9.png)我最近注意到很多机器人在拍卖行里放置物品。价格是0.01铁矿石或其他矿物。我每秒刷新一次以购买这些物品。但是我会保留很多.01项目，供机器人继续列出它们。我的眼睛累了，我不能长时间看拍卖行。那么是否有可能制作一个扫描物品并购买物品的机器人呢？功能如下
> > 
> > 1. 购买低于自定义价格的商品。例如，我只购买低于 0.02 的商品
> > 2. 购买后保留1或10件物品的数量。自定义保留项的数量。这将允许机器人继续列出项目。
> > 3. 自定义 X 秒。自动刷新拍卖行。
> > 4. 不要购买黑名单中的商品。
> > 5. 自定义购买列表以-----资源----资源
> > 6. 预防 AFK
> > 
> > 这并不紧急。只是想把它作为编程的甜蜜点。
> 
> 请为此打开一个新问题，而不是劫持线程。我也不认为这与钓鱼机器人有任何关系。

已经删除

**Comment by fkue587** [comment]
Deleted
