### ISSUE TITLE
Automate AH bids

### ISSUE THREAD

**Issue by nebelorz** [nebelorz/NW-Auto-Fishing#12]
![微信截图_20220119003741](https://user-images.githubusercontent.com/93835049/149981115-645c8813-b1ec-4295-92f6-ab7da8dd61a9.png)
I've recently noticed a lot of bots placing items in the auction house.
The price is 0.01 iron ore or other minerals.
I refreshed once a second to buy these items.
But I will keep a lot of .01 items for the bots to keep listing them.
My eyes get tired and I can't look at the auction house for long.
So is it possible to make a bot that scans items and buys them?
The function is as follows
1. Buy items below a custom price. For example, I only buy items under 0.02
2. Keep a quantity of 1 or 10 items after purchase. Customize the number of reserved items.
This will allow the robot to continue to list items.
3. Customize for X seconds. Automatically refresh the auction house. 
4. Do not buy items in the blacklist.
5. Customize the purchase list to -----RESOURCE----Raw Resources
6. Prevent AFK

This is not urgent. Just want to use it as a programming sweet spot.

_Originally posted by @fkue587 in https://github.com/nebelorz/New-World-Auto-Fishing/issues/11#issuecomment-1015604891_

**Comment by nebelorz** [comment]
Heya!

I was concerned about the hell it is to sell/buy certain items on New World and thought about it, but it'll take me quite a lot of time to develop something like this, as the first approach I'm thinking of, is using an OTR and parse user inputs, which I didn't used before and will also be another project totally different as this one. As you know, I'm currently occupied and my time is very limited so it's not likely going to happen, atleast in a short period of time ;S

**Comment by fkue587** [comment]
This is not urgent. Just do it when you have time. We're not trying to scan the entire auction house. Only scan the resource categories. I refresh the auction house manually. I used 200 gold coins and bought 3000 iron ore, 7000 wood. 2600 leather, and a lot of star iron ore , which is just too funny.

**Comment by fkue587** [comment]
Occasionally, because the fishing indicator is missing, or because the network is stuck for a long time, a determination should be added that there is no action for 5 minutes to reconnect the game. Prevent wasting time.
Winter is here and it's cold, please wear more clothes and wish you good health!

**Comment by fkue587** [comment]
The auction house project is a waste of time, it would be fine if it was used for practice, but after thinking about it, this project is not worth the time!

**Comment by nebelorz** [comment]
> The auction house project is a waste of time, it would be fine if it was used for practice, but after thinking about it, this project is not worth the time!

Yep, well, New World has the worst auction house I ever used tbh 😆, and a program that automates it would be cool, both buying and selling. 

Maybe in a future, idk! 😁

**Comment by fkue587** [comment]
https://www.bilibili.com/video/BV1MF411p7AN?from=search&seid=7286894879807654849&spm_id_from=333.337.0.0

The link above is the software that has been created You can watch the video haha
