### ISSUE TITLE
Still doesn't work. only works the first time.

### ISSUE THREAD

**Issue by fkue587** [nebelorz/NW-Auto-Fishing#2]
Only the first time you can fish normally, and after fishing you just repeatedly flip the rod. And after catching a fish, the pulling time is too short to cause fishing failure. please add multiple threads. and speed up the detection speed.

**Comment by nebelorz** [comment]
dang, I tested it and everything was flawless and speedy, let me check it this noon again.

I didn't add threads before 'cause it wasn't necessary (it was fast enough) but let me test it deeply.

**Comment by nebelorz** [comment]
Hi there @fkue587!
Took this noon to do some adjustments to the recognition in certain steps of the code, I found the errors you described and now it should work correctly everytime (tested personally for an hour)

I'm thinking to add a visible console to track the loops and steps, what do you think?
Maybe tomorrow I'll have some time to update and push it to Github. I'm also minding about making it a one file executable😋

[🎥 I'll leave a video here](https://vimeo.com/652691572)

**Comment by fkue587** [comment]
I'm really looking forward to your updates .
Resetting the perspective is a big deal.

**Comment by fkue587** [comment]
我建议把视角按键换为B.
Alt按键会导致更多问题.

**Comment by fkue587** [comment]
Suggest adding a fishing detail, so it's easy to debug.
In adding fishing stats. highlighting legendary fish and treasure chests.
Fish are classified as common fish, green fish and blue fish.

**Comment by nebelorz** [comment]
> Suggest adding a fishing detail, so it's easy to debug. In adding fishing stats. highlighting legendary fish and treasure chests. Fish are classified as common fish, green fish and blue fish.

I really like this one! Also I'll make a config file to set and customize the key bindings.

I would need some time to implement everything though, I'm working and studying at the same time, so its hard to find free time😅

Thanks a lot for all your feedback btw 🙃

**Comment by fkue587** [comment]
So let's start with a simple action.
Don't add new features yet.
First improve the old features and then add the new ones.
(onom.) laughing out loud




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nebelorz/New-World-Auto-Fishing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上11:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nebelorz/New-World-Auto-Fishing] Still doesn't work. only works the first time. (Issue #2)





  
Suggest adding a fishing detail, so it's easy to debug. In adding fishing stats. highlighting legendary fish and treasure chests. Fish are classified as common fish, green fish and blue fish.
  
I really like this one! Also I'll make a config file to set and customize the key bindings.
 
I would need some time to implement everything though, I'm working and studying at the same time, so its hard to find free timetime😅
 
Thanks a lot for all your feedback btw 🙃
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nebelorz** [comment]
Thanks for your feedback @fkue587!

Finally I updated the program, if you use it and find any more errors just open an issue and I'll try to fix it asap 🙃

**Comment by fkue587** [comment]
I'm glad to see the changes. thanks a lot. i tested it for half an hour and it worked.
1. When you just catch a fish, the timer is not counted, so you can click the mouse for a long time to shorten the fishing time.
2. If the program has already cast the fishing rod, click the mouse to cancel the rod, it will not automatically fishing.


I'll keep fishing for a long time and see if it goes wrong.


Good luck. #Thank you very much.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nebelorz/New-World-Auto-Fishing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 中午11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nebelorz/New-World-Auto-Fishing] Still doesn't work. only works the first time. (Issue #2)





 
Thanks for your feedback @fkue587!
 
I updated a new version of the program, if you use it and find any more errors just open an issue and I'll try to fix it asap 🙃
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fkue587** [comment]
// 18:07 LOOP# 47 //
[OK] BUBBLE CAST FOUND
[OK] FISH CAUGHT
[INFO] Casts until next repair:  8

// 18:07 LOOP# 48 //


Standing around here.I think we should add detection to prevent him from standing still without doing anything.

**Comment by fkue587** [comment]
If the water level is very high, to prevent AFK.
Code /sit 
I sit in water without dispersing afk!
And died of respiratory failure.

**Comment by nebelorz** [comment]
I'll keep an eye to these issues. 

The way the AFK is removed is a little bit tricky, as I don't want the character to move, maybe I can find another way to prevent it, but for now I would focus on fixing the loop to work correctly 100% of the times. 

The thing now is it doesn't re-starts the loop right?
I'll check it out today!

**Comment by fkue587** [comment]
It's 95% perfect now! Let me test more ...!
Let's solve the problem.

Do you play this game?

How did you get into programming? I want to learn programming too, for a better life.
I am just now starting to learn the basic variables. python programming language.
But English is not my native language. there are many difficulties.

**Comment by nebelorz** [comment]
Test the new version I uploaded @fkue587!

I don't play anymore to New World, tbh I ever played actively xP

It's been like a year that I am studying about programming, but I got a foundation already.
If you really like to learn things all the time, programming will be very rewarding!

**Comment by fkue587** [comment]
It's good not to play this game,this game is still young,lots of bugs.1 month ago it was surprisingly possible to copy gold.Very crazy.


I will continue to test the new version. thanks for making it.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nebelorz/New-World-Auto-Fishing"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 晚上10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nebelorz/New-World-Auto-Fishing] Still doesn't work. only works the first time. (Issue #2)





 
Test the new version I uploaded @fkue587!
 
I don't play anymore to New World, tbh I ever played actively xP
 
It's been like a year that I am studying about programming, but I got a foundation already.
 If you really like to learn things all the time, programming will be very rewarding!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nebelorz** [comment]
@fkue587! I just add a feature to wait 3 times to check for the cast, if not found, re-starts. This must solve the problem that sometimes it gets stuck due to input or server lag.

Update the code if you donwloaded it previously😋

**Comment by fkue587** [comment]
Add a time record. Let us know what happened. Approximately how long it takes to happen.
AFK you can add an option to move 0.2 seconds to the left and 0.2 seconds to the right.

Like this 
 SET_move = True # None -- jump in place.
                                 # True -- move left and right.

Because AFK is a 5 minute detection time.

----------------------    or   ------------------------

When adding AFK detection, if the first detection is unsuccessful 5-10 times, then the second detection is used. 

More than ten minutes. I was kicked out of the game. Ask to add a continue button to the bottom right corner of the detection and a play button to the bottom right corner.
That way you can go back into the game and continue.
I will continue to observe! good luck.

![1](https://user-images.githubusercontent.com/93835049/144728905-044e7dd3-69a4-49d3-9795-cdc18db5d1ea.png)

**Comment by fkue587** [comment]
// 08:07 LOOP# 1 //
-------------------More than ten minutes------------
// 08:22 LOOP# 31 //
[OK] BUBBLE CAST FOUND
[OK] FISH CAUGHT
[INFO] Casts until next repair:  29

// 08:27 LOOP# 32 //

AFK...   

/Sit does not work

**Comment by fkue587** [comment]
It should be added as a project so that I can know what version I use .
December 5, 2021 08:51:29 

Download the latest version to use

Test again
