### ISSUE TITLE
Now afk does not work. 

### ISSUE THREAD

**Issue by fkue587** [nebelorz/NW-Auto-Fishing#3]
Now afk does not work.
/sit does not work
Repeat for sit and jump.

**Comment by fkue587** [comment]
I found the problem in the last closed question.

**Comment by fkue587** [comment]
I learn to change your code. The following is code change. Very elementary. Ha ha


# Anti AFK
def anti_afk():
    pyAG.write('a')
    pyAG.write('a')
    pyAG.write('a')
    pyAG.write('a')
    time.sleep(0.3)
    pyAG.write('d')
    pyAG.write('d')
    pyAG.write('d')
    pyAG.write('d')
    time.sleep(0.3)
    pyDI.press((key_bindings.JUMP))
    time.sleep(1.5)

**Comment by nebelorz** [comment]
Check [the last release](https://github.com/nebelorz/New-World-Auto-Fishing/releases/) I uploaded, should be fine now!

Closing this issue as it should be solved now, thanks @fkue587!
