### ISSUE TITLE
Please add one. Kicked out of the game reconnect function.

### ISSUE THREAD

**Issue by fkue587** [nebelorz/NW-Auto-Fishing#4]
Please add one. Kicked out of the game reconnect function.

**Comment by fkue587** [comment]
This function is not an emergency function. It's perfect now, you can do it again when you have time.

**Comment by nebelorz** [comment]
Cool!
Good suggestions, I'll look to implement them and hope to update it soon (: thanks again for all your feedback @fkue587!

**Comment by fkue587** [comment]
You also need a shortcut button to pause and start.

**Comment by fkue587** [comment]
The time after the direction reset is a bit too long, I would like to know where to change it,
The loop time after a game of fishing is also a bit too long, and I'd like to know where to change it,
in order to increase efficiency.

I've searched functions.py, but I can't find the key.

Maybe I'm too inexperienced to change it.

**Comment by nebelorz** [comment]
You shouldn't change it, as it's the matter why sometimes the viewing re-positioning was not working correctly.

The loop is kinda the same thing, you've to wait until everything is resetted and checked, then the loop starts again. Anyways it doesn't take more than 2 seconds!

**Comment by fkue587** [comment]
> 

OK, let's keep the current configuration stable!
