### ISSUE TITLE
Doesn't recast after failed to reel the fish

### ISSUE THREAD

**Issue by MckenzieDavis** [nebelorz/NW-Auto-Fishing#5]
Sometimes when it failed/missed to reel when the notice appeared it seems that it doesn't recast and just stand still

**Comment by nebelorz** [comment]
Could you specify a little bit more? It should re-start everytime correctly even if it fails/misses to reel, as when there isn't the reeling animation it just re-starts the loop.

**Comment by MckenzieDavis** [comment]
I actually dont know but its a hit or miss, sometimes it does cast again sometimes it doesnt, i'll to find the thing that causing it

**Comment by nebelorz** [comment]
Do you got lag while running the program? Anyways it shouldn't been a problem 😕. 
I made 2k+ loops flawlessly with the last version. 

Tell me if this happens again, I'll check it out😛.

**Comment by MckenzieDavis** [comment]
If you mean lag by network probably yes, my ping is high due to no server in my region, which cause it to sometimes missed to reel when the fish is noticed

**Comment by nebelorz** [comment]
I'll check this out then, it should work correctly though but let me take a look 🙃

**Comment by fkue587** [comment]
Someone invites the group F1 and F2 selection icons overriding the fishing icon. this will stop working.
1. Want to add detection, select F2 to reject.
2. I would like to add a function to kick out of the game and reconnect.



I've cycled it 1K times and it's been stable with no problems.

**Comment by nebelorz** [comment]
Got it, I would update with the party rejection asap.
I would look to implement a reconnect function also.

**Comment by fkue587** [comment]
All that is needed is for opencv to recognize the kicked out of game button and the Connection button and play button.

**Comment by DavisMcKenzie** [comment]
@nebelorz I was able to replicate the problem easily, try and remove/rename fish_caught.png to pretend like it will miss the reel, and look it doesn't loop again, thats exactly the problem im having when it missed the fish caught.

**Comment by MckenzieDavis** [comment]
@nebelorz I was able to replicate the problem easily, try and change fish_caught.png image to pretend like it will miss the reel, and look it doesn't loop again, thats exactly the problem im having when it missed the fish caught.

**Comment by nebelorz** [comment]
@DavisMcKenzie check the [latest release](https://github.com/nebelorz/New-World-Auto-Fishing/releases)
It should be fine now, also speedier than before, so all pluses 😋

@fkue587 I implemented a group rejection feature too, a reconnect feature in a future though😪

**Comment by fkue587** [comment]
I will continue to test 
Looking forward to reconnecting the game
Thank you so much for all your work.

**Comment by MckenzieDavis** [comment]
@nebelorz Works perfectly now, are you sure you dont want to private this repo? the other one on github is bannable because of its public

**Comment by nebelorz** [comment]
@DavisMcKenzie Well, it's not supposed to be used on live servers, just for educational purposes and my own research using python. 

If I ever get a warning or a ban, I'll make it private/delete from my Github page, but I really like to get feedback from different people and solve these issues, it really forces me to learn new things 🙃

By the way, what's the reason it's bannable?

**Comment by fkue587** [comment]
如果被封禁,一定是被举报.我非常肯定.
或者亚马逊针下载并且分解这个程序,针对这个程序封禁.
但是很明显后者不会.

**Comment by MckenzieDavis** [comment]
> @DavisMcKenzie Well, it's not supposed to be used on live servers, just for educational purposes and my own research using python.
> 
> If I ever get a warning or a ban, I'll make it private/delete from my Github page, but I really like to get feedback from different people and solve these issues, it really forces me to learn new things 🙃
> 
> By the way, what's the reason it's bannable?

Oh I see, happy to help and giving feedbacks,I also try to learn the codes , all seems to be stable now and time for some features 😋, I see the skip animation part for uncommon+ fish, it's kinda hit and miss isnt it for that to work?

**Comment by nebelorz** [comment]
@DavisMcKenzie It should work all the times correctly, as it checks before pressing and releasing the "free look" key, but I found that New World sometimes bugs the key bindings, and the "free look" binding stops working until you restore to default the key bindings, and then suddenly works again😕

Maybe that's the problem, as I looped it for long times and it resets the camera all the times, but if it persists, leave some feedback and I'll take a look at it again

**Comment by MckenzieDavis** [comment]
The reset position camera works flawlessly, i just wondering you know the skip animation when you caught the fish and press left mouse to stop the animation? Im thinking of that

**Comment by MckenzieDavis** [comment]
The animation that you lift the fish, it even works for below tier uncommon fish

**Comment by nebelorz** [comment]
It skips the animation the same as the uncommon fish one without additional filters.

I cannot speed it up as it could leave to errors, e.g. to casting the rod again and restarting the next loop, which would be slower 😶
