### ISSUE TITLE
Hey, old friend, new problem.

### ISSUE THREAD

**Issue by fkue587** [nebelorz/NW-Auto-Fishing#6]
I created a new character and upgraded it to level 9.
I retested the fishing.

I take a tier 1 rod. Occasionally I lose fish due to lack of tension, or slow scanning speed.
Because of the low gear of the rod, the first pull was too little.

Increase the speed of detection and improve the first pulling power.

 !!!First time pulling power!!! Will increase the cycle speed.

Increase the first pull. The first pull can last a long time. about two seconds, I guess. about two seconds for the legendary rod.

The subsequent pulling power continued from the previous setup

Looking forward to the update.

Oh, and looking forward to the reconnect feature.

Good. Good day.

**Comment by nebelorz** [comment]
I tested with the tier 1 rod and it was okey for all the casts, in the last release I updated the function to reel the fish, and now it doesn't clicks once and then starts reeling, it starts already with pulling the reel and stops as soon as it reaches the "max reel", so if you're using the last release you shouldn't have that problem anymore (I tested it for 20 loops with a tier1 rod for the time I am writing this).

If the speed was okay before, it should be okay with a tier 1 rod, as the timer to catch the fish remains the same for all the rods so idk 🤔 I always caught the fish between middle of the timer.

I already implemented a treasure chest counter, and as soon as I finish the reconnect feature, I'll upload a new release.
Meanwhile I'll test it with a tier 1 rod all the times to check if there's any bug.

Thx for the feedback @fkue587!

**Comment by fkue587** [comment]
Remove all trophies and equipment, and empty the properties.

Are you adding attributes to focus.

 Only keep the level 1 fishing rod, because I created a low lv, he has nothing, only fishing rod and bait, so occasionally lost fish.

I upgraded to level 14, I started to use the level 2 fishing rod, no more problems with lost fish.

**Comment by nebelorz** [comment]
Hello @fkue587!

I've been testing with a brand new character and a tier 1 rod, and what possible happens to you (as it happened to me) is everytime you level up your territory standing, the notification stands just at the top where usually one leaves the "bubble" indicator, and it stays also on top of the bubble, so the program cannot detect it and it fails clicking when a fish has bitten the hook.

That should explain why when you leveled up, as your territory standing also levels up and it shows less frequently, you got less notifications and thus the program has been able to detect correctly the bubble icon.

Besides that, I always caught a fish (tier1 rod, no baits, no bonuses), so idk what could be failing 🤔.

Confirm me if this could be the case, if it couldn't be that, I can't do much more.

**Comment by MckenzieDavis** [comment]
Seems flawlessly working for me on new char

**Comment by fkue587** [comment]
I'm in parallel view, not looking down, so it's not a matter of bubbles. But this is not the point, a small problem, replaced the 2 levels of fishing rod in no error.

**Comment by fkue587** [comment]
I'm in parallel view, not looking down, so it's not a matter of bubbles. But this is not the point, a small problem, replaced the 2 levels of fishing rod in no error.

**Comment by nebelorz** [comment]
I suppose you're having hard times with the tension of the level 1 rod. I'll try to enhance the pull/release function to make it even faster.

A new release with reconnection and some improvements is near 😋

**Comment by fkue587** [comment]
Hey, old friend, can we wait for your update before Christmas?

**Comment by nebelorz** [comment]
Definitely, I'll give it a test today and if everything is fine it'll be released today 🙃

**Comment by nebelorz** [comment]
New release, added reconnection, treasure count and the reel loop is much more accurate and faster 😋

**Comment by fkue587** [comment]
After testing version 1.1 about 7 hours cycle 800 times, looking forward to the new version, the treasure chest count good function, but more simple is to open the backpack to view, ha ha!

**Comment by fkue587** [comment]
After testing version 1.1 about 7 hours cycle 800 times, looking forward to the new version, the treasure chest count good function, but more simple is to open the backpack to view, ha ha!

**Comment by nebelorz** [comment]
I'll temporary remove 1.1.1 release, I'll re-upload it this noon (in 10 hours aprox).
I noticed that there're some test options enabled >.<!

**Comment by fkue587** [comment]
Looking forward to your update, Merry Christmas.

**Comment by nebelorz** [comment]
[Release uploaded!](https://github.com/nebelorz/New-World-Auto-Fishing/releases/tag/v1.1.1)

Keep in mind that the reconnection function is in beta, as I made the disconnection check periodically, and not in a separate thread (as I am learning how to implement those 🙃 and will, in the future, implement a thread to check a disconnection), so keep an eye if you're using the reconnection unattended, as it wouldn't work 100% of the times.

I also improved the speed on the reel function, so it should be faster now, and should work flawless even with a level 1 rod, catching something almost always.
As with the reconnection, when I have settled the knowledge of the thread module, this will be multithreaded too.

Thanks again for your feedback @fkue587 and merry christmas to you too!

**Comment by nebelorz** [comment]
🔴 UPDATE

I've found some errors on the newly added regions to screenshots, download the [new version 1.1.2](https://github.com/nebelorz/New-World-Auto-Fishing/releases/tag/v1.1.2) if you were using the v1.1.1 to avoid errors!

**Comment by fkue587** [comment]
I will continue to test version 1.1.2. This version was missing the .BOT batch file, so I made a copy and continued testing!

**Comment by fkue587** [comment]
If you want to increase the speed.
You need to be at the point when the circle is about to be completed. Keep pressing the mouse. Do not care if it is orange or red.
The current version will stop when it reaches orange. When the circle is about to complete, it will slow down the speed.
After resetting the view. Wait time is shortened a little more. Will improve efficiency.
One more thing, if the real person fishing. Fishing to. The blue fish has a display animation, then press the left mouse button to cancel the animation. This point can be used as a reference.

**Comment by MckenzieDavis** [comment]
You have to understand that python pic recognition is not that fast + you need a good CPU to actually improve the recognition time

**Comment by fkue587** [comment]
> 你必须明白，python图片识别不是那么快+你需要一个好的CPU来实际提高识别时间

Multi-threading can be more efficient, that's for sure.
Python efficiency is already very high, and cpu does not have much to do with the multi-threaded to need a better cpu。
For newcomers to use has been very good!

**Comment by MckenzieDavis** [comment]
> If you want to increase the speed. You need to be at the point when the circle is about to be completed. Keep pressing the mouse. Do not care if it is orange or red. The current version will stop when it reaches orange. When the circle is about to complete, it will slow down the speed. After resetting the view. Wait time is shortened a little more. Will improve efficiency. One more thing, if the real person fishing. Fishing to. The blue fish has a display animation, then press the left mouse button to cancel the animation. This point can be used as a reference.

You can just create your own screenshot, capture the screenshot when the circle about to full yourself

**Comment by fkue587** [comment]
> > 如果要提高速度。你需要在圆圈即将完成的时候。继续按鼠标。不要在乎它是橙色还是红色。当前版本将在达到橙色时停止。当圆圈即将完成时，它会减慢速度。重置视图后。等待时间缩短了一点。将提高效率。还有一件事，如果真人钓鱼。钓鱼去。蓝色鱼有一个显示动画，然后按鼠标左键取消动画。这一点可以作为参考。
> 
> 您可以创建自己的屏幕截图，在圆圈即将填满自己时捕获屏幕截图

It's an exchange community to improve skills together, I'll try to learn, I just learned the basic variables, 😀 ! Merry Christmas!

**Comment by fkue587** [comment]
> 您可以创建自己的屏幕截图，在圆圈即将填满自己时捕获屏幕截图

It's an exchange community to improve skills together, I'll try to learn, I just learned the basic variables, 😀 ! Merry Christmas!

**Comment by nebelorz** [comment]
> I will continue to test version 1.1.2. This version was missing the .BOT batch file, so I made a copy and continued testing!

Use the new console.py instead, it will do the same as the old .bat, but you dont need any other program to keep the CMD always on top basically. 

In addition, to test if the circle is about to complete takes another screen recognition inside the reel loop, which will slow the performance and break the line on many casts, thats why the reel loop is a little "simpler", but maybe in a future using threads should be possible heh.

I'll keep learning and working on it! 

Thanks for your feedbacks @fkue587 and @DavisMcKenzie!

**Comment by fkue587** [comment]
I can't find the boot loader, so I'm using the BAT file from version 1.1 to boot 1.2.
Is there anything else I need to change?
Version 1.2 doesn't work very well, occasionally it doesn't detect AFK and gets kicked out of the game. And does not reconnect!!! I will continue to test the number of phishing compared to 1.1. and other bugs.

I looked at the images in the reconnect folder and I think the range of images detected is too small and should be increased. This would improve the probability of detecting text. Or just capture the whole confirmation button, which would have a higher success rate.

Error list.
1. Reconnecting is not stable!
2. Missing bat startup file.

**Comment by nebelorz** [comment]
I've tested tonight for 8 hours straight without an AFK disconnection 🤔 it should work as always tbh. 

Using large images to detect certain things is not recommended as it could lead to errors. The problem of the reconnect feature is that it should be checked constantly and it should be made with threads. 

For now, think as if the reconnect only works out if the reel loop, 'cause it's how is made now, if you're lucky and got a disconnection this way, the program should reconnect perfectly.

About the console, you only need to double click console.py and ready to go 😁

**Comment by fkue587** [comment]
I will continue testing.
The console.py is associated with another program, and I opened it as another file. 
I will continue to run 1.2 with the 1.1 bat program file

**Comment by fkue587** [comment]
![image](https://user-images.githubusercontent.com/93835049/147068075-a881d5e6-a8cd-4217-b24f-da347d2807b3.png)
用bat运行. 他站住不动...

**Comment by fkue587** [comment]
![image](https://user-images.githubusercontent.com/93835049/147071108-1713cfa0-9bea-48d8-92f8-42191190e4d9.png)
1.I run it from the Main Menu. After entering the game he stood still.
console.py is associated with the text file. It won't run.
I run it under CMD.

2.But after I entered the game, I stood on the beach. Re-run.
Then you can fish normally.

**Comment by nebelorz** [comment]
console.py basically opens CMD -> cls -> python main.py, so it's like running main.py from CMD manually.

The reconnect detects the backpack icon at the bottom to get the true value as the reconnection was succesfully, is it showing on your screen? Anyways I'll check it this noon just in case.

I'm a liitle confused about why the console isn't working for you ;S

**Comment by fkue587** [comment]
Reconnecting below does not show my backpack, because I set it not to show...

I turned on Show Backpack. Testing again. It's my fault.

**Comment by fkue587** [comment]
I have observed, now about 1 minute can fish 2 times.

**Comment by nebelorz** [comment]
More than before, right? 😁

**Comment by fkue587** [comment]
![image](https://user-images.githubusercontent.com/93835049/147113548-df750492-78bd-4e08-be76-b800527a90b1.png)
He blocked the green fish drift. No more fishing. Then he walked away. Fishing continued. Missed the tide of fish.

**Comment by nebelorz** [comment]
Yep, the reel and the images to recognize should always be on top, as if they're not, the program cannot find it.

I suggest you to put your camera angled to the top, so the reel stays at the bottom to avoid somebody block it or the quest tracker etc.

**Comment by fkue587** [comment]
Good idea, I use it successfully, no more errors.
It is our common goal to see if we can cycle faster.
