### ISSUE TITLE
chest counter funked?

### ISSUE THREAD

**Issue by wade217** [nebelorz/NW-Auto-Fishing#8]
awesome work! happy holidays and all that!

chest counter doesnt seem to be working for me anymore with the most recent version. anyone else experiencing this? it's easy enough to open my inventory and check. this was just something i noticed.

**Comment by nebelorz** [comment]
Hello @wade217! Thanks!

Check the [last release](https://github.com/nebelorz/New-World-Auto-Fishing/releases/tag/v1.1.51)

It worked for me until now, let me hear if this version fixed the issue for you 🙃

Happy holidays for you too!

**Comment by nebelorz** [comment]
Check [this build](https://github.com/nebelorz/New-World-Auto-Fishing/files/7796482/New-World-Auto-Fishing.v1.1.6.zip)!
I've tested the counter and works for me 🤔
Tell me if the issue persists and I could find another way to count the chests!

Happy new year btw!😎
