### ISSUE TITLE
1

### ISSUE THREAD

**Issue by fkue587** [nebelorz/NW-Auto-Fishing#9]
home should be start not pause and continue
end is to end all code
Restart the fishing, the counter continues to count.

restart without baiting

I don't know why when I first started to use 1.16, I cast the rod especially quickly after resetting the direction, but after ENDing for some time and starting again, it seems that the time after resetting the direction will be extended.

**Comment by nebelorz** [comment]
I'll check if pausing/resuming adds some kind of delay, but there's nothing that the hotkeys that could affect it, as just adds a wait until you resume it again. 

The thing with hotkeys is just to pause and resume as I don't really want to have something in the background that re-runs the script on keypress 😅
